### ISSUE TITLE
name 'unicode' is not defined with Python3

### ISSUE THREAD

**Issue by keepworld** [napalm-automation/napalm-iosxr#103]
### Description of Issue/Question
When using napalm methods on iosxr platform & python3, it returns "name 'unicode' is not defined" as unicode does not exist in Python3.

get_interfaces() works whereas get_interfaces_ip() not for example.

### napalm-iosxr version
```
napalm-iosxr==0.4.2
```

### IOS-XR version and platform details
```
Fri Feb  3 11:43:31.498 CEST

Cisco IOS XR Software, Version 5.1.3[Default]
Copyright (c) 2015 by Cisco Systems, Inc.

ROM: System Bootstrap, Version 2.04(20140227:092320) [ASR9K ROMMON],

CORE-01.PAR-3 uptime is 39 weeks, 2 days, 18 hours, 15 minutes
System image file is "bootflash:disk0/asr9k-os-mbi-5.1.3.sp2-1.0.0/0x100000/mbiasr9k-rp.vm"

cisco ASR9K Series (P4040) processor with 8388608K bytes of memory.
P4040 processor at 1500MHz, Revision 2.0
ASR-9001 Chassis

2 Management Ethernet
8 TenGigE
20 GigabitEthernet
8 DWDM controller(s)
8 WANPHY controller(s)
219k bytes of non-volatile configuration memory.
2868M bytes of hard disk.
3915760k bytes of disk0: (Sector size 512 bytes).
```

### Steps to Reproduce the Issue
driver = get_network_driver('iosxr')
device = driver(node, login, password)
int_l3 = device.get_interfaces_ip()

### Error Traceback
```
name 'unicode' is not defined
```

**Comment by mirceaulinic** [comment]
Hi @poupsmaster - thanks for reporting this!

Can you please list all the methods failing and their complete error traceback? It is equally important to know how, but also where they are failing.

**Comment by keepworld** [comment]
get_arp_table()
get_bgp_config()
get_bgp_neighbors()
get_interfaces_ip()
get_lldp_neighbors()
get_lldp_neighbors_details()
get_mac_address_table()

The above methods give the below error :
  File "/Users/r.pouppeville/PycharmProjects/formation/flask-vuejs-test/app/utils/net.py", line 243, in asr_napalm
    bgp = device.get_bgp_config()
  File "/anaconda/lib/python3.5/site-packages/napalm_iosxr/iosxr.py", line 810, in get_bgp_config
    'type': unicode(bgp_type),
NameError: name 'unicode' is not defined

As a temporary workaround, removing calls to 'unicode' in 'iosxr.py' seems to do the trick :
            bgp_config[group_name] = {
                'apply_groups': [],  # on IOS-XR will always be empty list!
                'description': description,
                'local_as': local_as,
                'type': unicode(bgp_type),  --> type': bgp_type,

**Comment by mirceaulinic** [comment]
Hi @poupsmaster,

Python3 support has been introduced in napalm-iosxr 0.4.3 - see https://github.com/napalm-automation/napalm-iosxr/releases/tag/0.4.3
You are currently running 0.4.2, please upgrade.

**Comment by keepworld** [comment]
Hi many thanks !
