### ISSUE TITLE
is_enabled set to false in get_bgp_neighbors

### ISSUE THREAD

**Issue by ogenstad** [napalm-automation/napalm-iosxr#105]
The is_enabled field always seems to be set to false. Might be that the ConnectionAdminStatus (https://github.com/napalm-automation/napalm-iosxr/blob/develop/napalm_iosxr/iosxr.py#L355-L358) never gets set to "1" in the xml response or that some other field should be used, or different values.

**Comment by mirceaulinic** [comment]
I believe there isn't a better way unfortunately.
I have to close this issue @ogenstad - if you see any solution, please let's discuss in the main repo, after the reunification. Thanks!
