### ISSUE TITLE
`get_bgp_neighbors_detail` gets `unexpected EOF`

### ISSUE THREAD

**Issue by wasabi222** [napalm-automation/napalm-iosxr#140]
### Description of Issue/Question

ASR version 5.1.3, issuing a `get_bgp_neighbors_detail` receives an error:
 File "<string>", line unknown

    ^
SyntaxError: unexpected EOF while parsing

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[ x ] Yes
[ ] No

### Setup
```
napalm-iosxr==0.5.4
napalm-base==0.23.3
pyIOSXR==0.52
```
### napalm-iosxr version
(Paste verbatim output from `pip freeze | grep napalm-iosxr` between quotes below)

```
napalm-iosxr==0.5.4
```

### IOS-XR version and platform details
(Paste the complete verbatim output from `show version brief` between quotes below)

```
#sh ver br
Fri Aug  4 14:09:36.675 EDT

Cisco IOS XR Software, Version 5.1.3[Default]
Copyright (c) 2016 by Cisco Systems, Inc.

ROM: System Bootstrap, Version 0.73(c) 1994-2012 by Cisco Systems,  Inc.

# uptime is 30 weeks, 7 hours, 4 minutes
System image file is "disk0:asr9k-os-mbi-5.1.3.sp10-1.0.0/0x100305/mbiasr9k-rsp3.vm"

cisco ASR9K Series (Intel 686 F6M14S4) processor with 6291456K bytes of memory.
Intel 686 F6M14S4 processor at 2127MHz, Revision 2.174
ASR 9006 AC Chassis with PEM Version 2

4 Management Ethernet
40 TenGigE
40 DWDM controller(s)
40 WANPHY controller(s)
503k bytes of non-volatile configuration memory.
6111M bytes of hard disk.
12510192k bytes of disk0: (Sector size 512 bytes).
12510192k bytes of disk1: (Sector size 512 bytes).
```

### Steps to Reproduce the Issue
device.get_bgp_neighbors_detail()
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
  File "<string>", line unknown

    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by ktbyers** [comment]
@wasabi222 Do you have a Python stack trace (should be quite a bit more).

**Comment by wasabi222** [comment]
@ktbyers  

```
 Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 153, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/napalm_iosxr/iosxr.py", line 910, in get_bgp_neighbors_detail
            neighbor, 'IsLocalAddressConfigured', 'false').title())
          File "<string>", line 0

            ^
        SyntaxError: unexpected EOF while parsing
```

**Comment by wasabi222** [comment]
I did a bit more digging on this and the method executes fine on the python interpreter, this error actually occurs when I issue a napalm call from salt, so the issue appears to be with that implementation and not the driver itself. My apologies. Closing this out and opening in the correct location.
