### ISSUE TITLE
napalm-iosxr egg is not dir

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-iosxr#19]
It is very interesting how the `napalm-iosxr` library is installed in a different way. Although we fixed `get_network_driver` with https://github.com/napalm-automation/napalm-base/pull/24, there are still some serious issues alive (my comments https://github.com/napalm-automation/napalm/pull/232#issuecomment-209450768 and https://github.com/napalm-automation/napalm/pull/232#issuecomment-209465739).

`napalm-iosxr` is the only lib having the egg installed as file, not as directory:

``` bash
(virtualenv)mircea@36netops1:/usr/local/salt/virtualenv/lib/python2.7/site-packages$ ls -la | grep napalm | grep junos
drwxr-xr-x   3 mircea mircea      60 May 13 11:48 napalm_junos
drwxr-xr-x   4 mircea mircea      80 May 13 10:00 napalm_junos-0.2.0-py2.7.egg
(virtualenv)mircea@36netops1:/usr/local/salt/virtualenv/lib/python2.7/site-packages$ ls -la | grep napalm | grep iosxr
drwxr-xr-x   2 mircea mircea     120 May 13 14:12 napalm_iosxr
-rw-r--r--   1 mircea mircea   35689 May 12 14:52 napalm_iosxr-0.2.0-py2.7.egg
drwxr-xr-x   2 mircea mircea     140 May  5 09:57 napalm_iosxr-0.2.0-py2.7.egg-info
```

Which has direct implications in methods such as `load_template`:

``` python
>>> i.load_template('set_ntp_peers', peers=['192.168.0.1'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/napalm_base-0.14.1-py2.7.egg/napalm_base/base.py", line 104, in load_template
    **template_vars)
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/napalm_base-0.14.1-py2.7.egg/napalm_base/helpers.py", line 31, in load_template
    path=template_dir_path
napalm_base.exceptions.DriverTemplateNotImplemented: Config template dir does not exist: /usr/local/salt/virtualenv/lib/python2.7/site-packages/napalm_iosxr-0.2.0-py2.7.egg/napalm_iosxr/templates.
                        Please create it and add driver-specific templates.
```

**Comment by mirceaulinic** [comment]
Worths mentioning:
- This happens when the library is installed using `python setup.py install`
- Installing the public library with `pip install napalm-iosxr` works fine
- Installing from your local custom with `pip install -e /path/to/your/dev/version/` works fine again. But this is just bypassing the core issue. As all the others work properly using `python setup.py install` this one should work too, unless there are some small details we are missing.

**Comment by dbarrosop** [comment]
Do you have any clue why this is happening? All `setup.py`look exactly the same.

**Comment by mirceaulinic** [comment]
Unfortunately no, I still don't have any idea why :(

**Comment by mirceaulinic** [comment]
And yes, I checked that too, apart from driver-specific details,  all `setup.py` are exactly the same. That's even more odd.

**Comment by mirceaulinic** [comment]
I am not sure #20 was enough to fix this, can we please keep it open?

**Comment by dbarrosop** [comment]
Sure, I think it was closed automatically by the power of references.

**Comment by mirceaulinic** [comment]
Now it is dir...

``` bash
(hack2016)mircea@36netops3:~$ ls -la /state/home/mircea/hack2016/lib/python2.7/site-packages | grep iosxr
drwxr-xr-x  5 mircea    100 Sep 18 16:25 napalm_iosxr-0.2.2-py2.7.egg/
```
