### ISSUE TITLE
iosxr driver get_interfaces is_enabled returns the same as is_up

### ISSUE THREAD

**Issue by wasabi222** [napalm-automation/napalm-iosxr#34]
I was looking to see if I could check to see whether a port was down due to it being disabled, or for another reason, but it looks like even if the port is enabled and down, is_enabled is set to false. 

This seems to be because is_enabled is just being copied over from is_up:
https://github.com/napalm-automation/napalm-iosxr/blob/develop/napalm_iosxr/iosxr.py#L203
is_up = (find_txt(interface_tree, 'LineState') == 'IM_STATE_UP')
is_enabled = (find_txt(interface_tree, 'LineState') == 'IM_STATE_UP')

**Comment by mirceaulinic** [comment]
Hi @wasabi222 thanks for reporting this! And sorry for delay. I really missed this one.
