### ISSUE TITLE
Add support for dedicated XML agent support (with TLS)

### ISSUE THREAD

**Issue by jejenone** [napalm-automation/napalm-iosxr#43]
It is supposedly faster than TTY agent.

http://www.cisco.com/c/en/us/td/docs/ios_xr_sw/iosxr_r4-1/xml/programming/guide/xl41apidoc/xl41noti.html#wp1068023

**Comment by mirceaulinic** [comment]
Thanks @jejenone for pointing this out! This is something we should have in mind and probably should be addressed during the hackathon :)

**Comment by jejenone** [comment]
I wish I had the time to help on this during the hackathon. But I don't.

**Comment by mirceaulinic** [comment]
Opened ticket under pyiosxr: https://github.com/fooelisa/pyiosxr/issues/26
