### ISSUE TITLE
Migrate tests to new testing framework

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-iosxr#46]
See details in the parent issue napalm-automation/napalm-base#99

**Comment by ogenstad** [comment]
@mirceaulinic, I see this is assigned to you. I figured you might not have started yet. So I've added PR #69. 

There's an old test for get_lldp_neighbors(), which includes a monkey patch for pyIOSXR. However I don't see the actual function in pyIOSXR. Do you know if this is something which have been removed?

**Comment by mirceaulinic** [comment]
Hey @ogenstad - yes, I have assigned this one to myself. No progress so far, thanks for looking into this!

> There's an old test for get_lldp_neighbors(), which includes a monkey patch for pyIOSXR. However I don't see the actual function in pyIOSXR. Do you know if this is something which have been removed?

```get_lldp_neighbors``` is a very old function which does exactly the opposite of the network automation: scraping the CLI: https://github.com/napalm-automation/napalm-iosxr/blob/develop/napalm_iosxr/iosxr.py#L593. As you can see it calls ```show_lldp_neighbors()``` from pyIOSXR and a [dirty hack](https://github.com/fooelisa/pyiosxr/blob/master/pyIOSXR/iosxr.py#L96) transforms this into the CLI command ```show lldp neighbors``` and retrieves the raw text output.

**Comment by ogenstad** [comment]
Thanks! Didn't see the hack.

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-iosxr/commit/a04fbcf942b9fe902da2a222661b158baf8be1c1
